[package]
name = "connorcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# My Crates :P
afire = "0.2.0"
simple_config_parser = "1.0.0"

ureq = "2.3.0"
rand = "0.8.4"
