[package]
name = "connorcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# My Crates :P
# afire = "0.2.0"
afire = { git = "https://github.com/Basicprogrammer10/afire.git", branch = "0.2.1", features = ["serve_static"] }
simple_config_parser = "1.0.0"

# (En / De)codeing
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"

# Hashing
sha2 = "0.9.8"

# Other
lazy_static = "1.4.0"
chrono = "0.4.19"
ureq = "2.3.0"
rand = "0.8.4"
